# Generated by Django 4.2.7 on 2025-07-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grua_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionservicio',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='asignacionservicio',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='asignacionservicio',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Configuracion',
        ),
        migrations.RemoveField(
            model_name='historialpago',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='conductor_asignado',
        ),
        migrations.AlterModelOptions(
            name='codigoverificacion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='solicitudservicio',
            options={'ordering': ['-fecha_solicitud']},
        ),
        migrations.DeleteModel(
            name='AsignacionServicio',
        ),
        migrations.DeleteModel(
            name='Conductor',
        ),
        migrations.DeleteModel(
            name='HistorialPago',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
