# Generated by Django 5.2.4 on 2025-07-17 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grua_app', '0002_remove_asignacionservicio_conductor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_base', models.DecimalField(decimal_places=2, default=15000, max_digits=10)),
                ('tarifa_por_km', models.DecimalField(decimal_places=2, default=1200, max_digits=10)),
                ('tarifa_minima', models.DecimalField(decimal_places=2, default=20000, max_digits=10)),
                ('hora_inicio_operacion', models.TimeField(default='07:00')),
                ('hora_fin_operacion', models.TimeField(default='22:00')),
                ('radio_cobertura_km', models.DecimalField(decimal_places=2, default=50, max_digits=6)),
                ('tiempo_maximo_espera_minutos', models.IntegerField(default=60)),
                ('email_notificaciones', models.EmailField(default='admin@gruaexpress.cl', max_length=254)),
                ('enviar_sms', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.AlterModelOptions(
            name='codigoverificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Código de Verificación', 'verbose_name_plural': 'Códigos de Verificación'},
        ),
        migrations.AlterModelOptions(
            name='solicitudservicio',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Solicitud de Servicio', 'verbose_name_plural': 'Solicitudes de Servicio'},
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='marca_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='modelo_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='placa_vehiculo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia_conducir', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('vehiculo_asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('authorization_code', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grua_app.solicitudservicio')),
            ],
            options={
                'verbose_name': 'Historial de Pago',
                'verbose_name_plural': 'Historiales de Pago',
                'ordering': ['-fecha_transaccion'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('grua_liviana', 'Grúa Liviana'), ('grua_pesada', 'Grúa Pesada'), ('auxilio_mecanico', 'Auxilio Mecánico')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('capacidad_carga', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_servicio', 'En Servicio'), ('mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], default='disponible', max_length=20)),
                ('latitud_actual', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_actual', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grua_app.conductor')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('en_camino', 'En Camino'), ('en_sitio', 'En Sitio'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='asignada', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_viaje', models.DateTimeField(blank=True, null=True)),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grua_app.solicitudservicio')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grua_app.conductor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grua_app.vehiculo')),
            ],
            options={
                'verbose_name': 'Asignación de Servicio',
                'verbose_name_plural': 'Asignaciones de Servicio',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
