# Generated by Django 5.2.4 on 2025-07-22 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grua_app', '0003_configuracion_alter_codigoverificacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium'), ('vip', 'VIP')], max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicios_incluidos', models.IntegerField(help_text='Cantidad de servicios incluidos por mes (0 = ilimitado)')),
                ('descuento_porcentaje', models.IntegerField(default=0, help_text='Porcentaje de descuento en servicios')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Membresía',
                'verbose_name_plural': 'Tipos de Membresías',
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('suspendida', 'Suspendida')], default='activa', max_length=20)),
                ('servicios_utilizados', models.IntegerField(default=0, help_text='Servicios utilizados en el mes actual')),
                ('auto_renovar', models.BooleanField(default=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL)),
                ('tipo_membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grua_app.tipomembresia')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PagoMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('webpay', 'WebPay'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('token_webpay', models.CharField(blank=True, max_length=100, null=True)),
                ('orden_compra', models.CharField(max_length=50, unique=True)),
                ('numero_transferencia', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante_transferencia', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('datos_adicionales', models.JSONField(blank=True, help_text='Datos adicionales del pago', null=True)),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='grua_app.membresia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Membresía',
                'verbose_name_plural': 'Pagos de Membresías',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
