# Generated by Django 5.2.4 on 2025-08-12 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grua_app', '0004_tipomembresia_membresia_pagomembresia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagomembresia',
            name='token_webpay',
        ),
        migrations.RemoveField(
            model_name='solicitudservicio',
            name='webpay_authorization_code',
        ),
        migrations.RemoveField(
            model_name='solicitudservicio',
            name='webpay_buy_order',
        ),
        migrations.RemoveField(
            model_name='solicitudservicio',
            name='webpay_token',
        ),
        migrations.AlterField(
            model_name='historialpago',
            name='metodo_pago',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pagomembresia',
            name='metodo_pago',
            field=models.CharField(choices=[('mercadopago_card', 'Tarjeta (Mercado Pago)'), ('mercadopago_transfer', 'Transferencia (Mercado Pago)'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('pendiente_pago', 'Pendiente de Pago'), ('pago_rechazado', 'Pago Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('mercadopago_card', 'Tarjeta (Mercado Pago)'), ('mercadopago_transfer', 'Transferencia (Mercado Pago)')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='MercadoPagoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercadopago_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('preference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_id', models.CharField(default='CLP', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('authorized', 'Autorizado'), ('in_process', 'En proceso'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('charged_back', 'Contracargo')], default='pending', max_length=20)),
                ('status_detail', models.CharField(blank=True, max_length=100)),
                ('payment_method_type', models.CharField(choices=[('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito'), ('bank_transfer', 'Transferencia Bancaria'), ('cash', 'Efectivo'), ('wallet', 'Billetera Digital')], max_length=20)),
                ('payment_method_id', models.CharField(blank=True, max_length=30)),
                ('installments', models.IntegerField(default=1)),
                ('payer_email', models.EmailField(max_length=254)),
                ('payer_identification_type', models.CharField(default='RUN', max_length=10)),
                ('payer_identification_number', models.CharField(max_length=20)),
                ('external_reference', models.CharField(max_length=100, unique=True)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('solicitud_servicio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mercadopago_payment', to='grua_app.solicitudservicio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago Mercado Pago',
                'verbose_name_plural': 'Pagos Mercado Pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='historialpago',
            name='mercadopago_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grua_app.mercadopagopayment'),
        ),
        migrations.AddField(
            model_name='pagomembresia',
            name='mercadopago_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grua_app.mercadopagopayment'),
        ),
        migrations.CreateModel(
            name='MercadoPagoWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(max_length=100, unique=True)),
                ('webhook_type', models.CharField(choices=[('payment', 'Payment'), ('plan', 'Plan'), ('subscription', 'Subscription'), ('invoice', 'Invoice'), ('point_integration_wh', 'Point Integration')], max_length=30)),
                ('action', models.CharField(blank=True, max_length=50)),
                ('data_id', models.CharField(max_length=100)),
                ('raw_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grua_app.mercadopagopayment')),
            ],
            options={
                'verbose_name': 'Webhook Mercado Pago',
                'verbose_name_plural': 'Webhooks Mercado Pago',
                'ordering': ['-created_at'],
            },
        ),
    ]
