# Generated by Django 5.2.4 on 2025-08-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grua_app', '0005_remove_pagomembresia_token_webpay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('pendiente_pago', 'Pendiente de Pago'), ('pendiente_confirmacion', 'Pendiente de Confirmación'), ('pago_rechazado', 'Pago Rechazado')], default='pendiente', max_length=25),
        ),
    ]
