# Generated by Django 5.2.4 on 2025-08-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grua_app', '0007_alter_solicitudservicio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('suspendida', 'Suspendida')], default='activa', max_length=20),
        ),
    ]
