# Generated by Django 5.2.4 on 2025-09-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grua_app', '0008_alter_membresia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='tipo_servicio_categoria',
            field=models.CharField(choices=[('grua', 'Servicio de Grúa'), ('asistencia', 'Asistencia Mecánica'), ('bateria', 'Carga de Batería')], default='grua', help_text='Tipo de servicio solicitado', max_length=20),
        ),
    ]
