# Generated by Django 5.2.4 on 2025-09-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grua_app', '0009_solicitudservicio_tipo_servicio_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='tarifa_base_aplicada',
            field=models.IntegerField(default=30000, help_text='Tarifa base aplicada al momento de la solicitud'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='tarifa_km_aplicada',
            field=models.IntegerField(default=1500, help_text='Tarifa por km aplicada al momento de la solicitud'),
        ),
    ]
