# Generated by Django 5.2.4 on 2025-09-05 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grua_app', '0010_solicitudservicio_tarifa_base_aplicada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Si el servicio está disponible o no')),
                ('mensaje_personalizado', models.CharField(blank=True, default='Servicio temporalmente no disponible', help_text='Mensaje que se muestra cuando el servicio no está disponible', max_length=200)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilidad del Servicio',
                'verbose_name_plural': 'Disponibilidad del Servicio',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
