# Generated by Django 5.2.4 on 2025-09-05 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grua_app', '0011_disponibilidadservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('nueva_solicitud', 'Nueva Solicitud'), ('pago_confirmado', 'Pago Confirmado'), ('servicio_completado', 'Servicio Completado')], max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grua_app.solicitudservicio')),
            ],
            options={
                'verbose_name': 'Notificación Admin',
                'verbose_name_plural': 'Notificaciones Admin',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
