# Generated by Django 5.2.4 on 2025-09-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grua_app', '0012_notificacionadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Grúa Style', max_length=100)),
                ('rut_empresa', models.CharField(default='77.971.506-K', max_length=12)),
                ('direccion_empresa', models.TextField(default='Santiago, Chile')),
                ('telefono_empresa', models.CharField(default='+56 9 8908 5315', max_length=20)),
                ('email_empresa', models.EmailField(default='contacto@gruastyle.com', max_length=254)),
                ('generar_reportes_automaticos', models.BooleanField(default=True)),
                ('dia_generacion_reporte', models.IntegerField(default=1, help_text='Día del mes para generar reporte automático')),
                ('meta_servicios_mes', models.IntegerField(default=100, help_text='Meta de servicios por mes')),
                ('meta_ingresos_mes', models.DecimalField(decimal_places=2, default=3000000, help_text='Meta de ingresos por mes', max_digits=10)),
                ('alerta_solicitudes_pendientes', models.IntegerField(default=5, help_text='Alertar cuando hay X solicitudes pendientes')),
            ],
            options={
                'verbose_name': 'Configuración Empresa',
                'verbose_name_plural': 'Configuración Empresa',
            },
        ),
        migrations.CreateModel(
            name='EstadisticaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('servicios_grua', models.IntegerField(default=0)),
                ('servicios_asistencia', models.IntegerField(default=0)),
                ('total_servicios', models.IntegerField(default=0)),
                ('ingresos_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('solicitudes_pendientes', models.IntegerField(default=0)),
                ('solicitudes_confirmadas', models.IntegerField(default=0)),
                ('solicitudes_completadas', models.IntegerField(default=0)),
                ('pagos_efectivo', models.IntegerField(default=0)),
                ('pagos_transferencia', models.IntegerField(default=0)),
                ('pagos_tarjeta', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estadística Diaria',
                'verbose_name_plural': 'Estadísticas Diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReporteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('total_servicios_grua', models.IntegerField(default=0)),
                ('ingresos_grua', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('promedio_servicio_grua', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_asistencias', models.IntegerField(default=0)),
                ('ingresos_asistencias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('promedio_asistencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_servicios', models.IntegerField(default=0)),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingresos_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingresos_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingresos_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nuevas_membresias', models.IntegerField(default=0)),
                ('ingresos_membresias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('generado_automaticamente', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reporte Mensual',
                'verbose_name_plural': 'Reportes Mensuales',
                'ordering': ['-año', '-mes'],
                'unique_together': {('año', 'mes')},
            },
        ),
    ]
